### ISSUE TITLE
Can i flash/update soldered the SST39SF010?

### ISSUE THREAD

**Issue by DirkBree** [LIV2/RIPPLE-IDE#1]
Of course I can desolder and programme the IC for an update but that is impractical.
Hence the question of whether it can be programmed in circuit in any way?

**Comment by LIV2** [comment]
Hi @DirkBree,

You can update the flash at any time simply by booting the latest lide-update boot disk here: https://github.com/LIV2/lide.device/releases

This will program the flash in-system and can do so even if the flash is blank.

I will add this info to the Readme

**Comment by DirkBree** [comment]
Hi @LIV2,
oh cool, this is a great solution and thanks for your answer.
